import { ResearchEntry, FalsificationCase } from '../types/research';

export const INITIAL_RESEARCH_ENTRIES: ResearchEntry[] = [
  {
    id: 'fathertime-zenodo-18322841',
    title: 'Gravity Without Spacetime & Digital Crystal Protocol (DCP)',
    category: 'Digital-Crystal',
    summary: 'The foundational treatise demonstrating gravity as a deterministic spatial-density gradient across a discrete lattice, replacing Riemannian metric curvature with the Digital Crystal Protocol (DCP) notarization.',
    content: 'Full formal derivation removing the continuous tensor field assumption in Einstein General Relativity. Spacetime curvature is reformulated as emergent refraction across discrete crystal coordinates governed by Size, Density, Kinetics, and Position (SDKP). Includes absolute cryptographic provenance sealing under Dallas’s Code mod-9 prime locks and zero-drift state verification (1.000000 coherence).',
    equations: 'T_{evolution} = f(S, D, K, P)\n\\nabla_{discrete} \\rho = \\frac{\\Delta \\rho}{\\Delta x + 0.1}\n\\text{digital\\_root} = \\text{prime\\_lock} \\pmod 9\n\\mathcal{C}_{decoherence} = 1.000000',
    dataPoints: 'Zenodo Record ID: 18322841 | DOI: 10.5281/zenodo.18322841 | Prime Lock: 104729 | Digital Root Harmonic: 5 | Zero-Crossing Offset: +0.1000 | Decoherence Score: 1.000000 | Lattice Geometry: 13-Node Face-Centered Cubic (FCC)',
    authorUid: 'fathertime-origin-smith',
    authorEmail: 'dallasnamiyadaddy@gmail.com',
    gitRepo: 'https://github.com/FatherTimeSDKP/Digital-Crystal-protocol',
    zenodoDoi: '10.5281/zenodo.18322841',
    osfId: 'osf.io/fathertime-dcp-core',
    xPostUrl: 'https://x.com/FatherTimes369v/status/1789000000000000001',
    dcpSealHash: 'a7c39f029e84b29158c3a19ffea823b107df2e3a19bc8201de399a0d84f88129',
    primeLock: 104729,
    mod9Harmonic: 5,
    decoherenceScore: 1.000000,
    createdAt: '2024-03-15T14:32:00.000Z',
    updatedAt: '2026-09-28T22:00:00.000Z',
    tags: ['Gravity', 'DCP', 'Zenodo-18322841', 'Dallas-Code', 'Deterministic'],
    isPinned: true
  },
  {
    id: 'fathertime-metatron-fcc-13',
    title: 'Metatron 13-Node Face-Centered Cubic (FCC) Lattice & SD-N-EOS-QCC',
    category: 'SD-N-EOS-QCC',
    summary: 'Geometric formulation of the universe as a 13-node spatial array. Replaces continuous manifold assumptions with 1 origin node and 12 close-packed sphere vertices.',
    content: 'The 13-node Metatron array configures 1 central observer node (0,0,0) and 12 outer coordinate vectors (±1, ±1, 0), (±1, 0, ±1), (0, ±1, ±1). Shape, Dimension, and Number (SD&N) governs spatial pre-processing, while Equation of State (EOS) and Quantum Coherence Coordinates (QCC) ensure discrete wave-packet propagation without probability cloud collapse.',
    equations: '\\vec{r}_0 = (0,0,0)\n\\vec{r}_{1..12} = \\frac{1}{\\sqrt{2}} (\\pm 1, \\pm 1, 0)_{perm}\n\\Phi_{Metatron}(k) = \\sum_{n=0}^{12} \\omega_n e^{i \\mathbf{k} \\cdot \\vec{r}_n}\n\\text{Coordination Number} = 12',
    dataPoints: 'FCC Coordination Number: 12 + 1 = 13 Nodes | Packing Fraction: 0.74048 | Nearest Neighbor Distance: d = a / sqrt(2) | Harmonic Mod-9 Distribution: {1, 4, 7, 2, 5, 8, 3, 6, 9} | Zero Singularities: Confirmed via +0.1 offset',
    authorUid: 'fathertime-origin-smith',
    authorEmail: 'dallasnamiyadaddy@gmail.com',
    gitRepo: 'https://github.com/FatherTimeSDKP/FatherTimeSDKP-SD-N-EOS-QCC',
    zenodoDoi: '10.5281/zenodo.18322841',
    osfId: 'osf.io/metatron-13fcc-array',
    xPostUrl: 'https://x.com/FatherTimes369v/status/1791230491029192000',
    dcpSealHash: '4f29a9b0811e739cdbe003184ac3619fbdf18903c732910fa8e41793792039ab',
    primeLock: 104743,
    mod9Harmonic: 1,
    decoherenceScore: 1.000000,
    createdAt: '2024-04-02T10:14:00.000Z',
    updatedAt: '2026-09-28T22:00:00.000Z',
    tags: ['Metatron', 'FCC-13', 'SD-N', 'EOS-QCC', 'Lattice'],
    isPinned: true
  },
  {
    id: 'fathertime-dallas-code-mod9',
    title: 'Dallas’s Code: Mod-9 Prime Reduction & Harmonic Phase Locking',
    category: 'Dallas-Code',
    summary: 'The universal discrete synchronization harmonic: prime lock values reduce through modulo 9 to terminate chaotic drift and lock single-digit phase rotations {1..9}.',
    content: 'Dallas’s Code eliminates the non-terminating transcendental expansions that plague classical physics. By reducing large prime keys mod 9, physical states achieve fixed cyclic invariants. In cryptographic notarization, Dallas’s Code enforces harmonic gating on token hashes and SHA-256 seal digests.',
    equations: 'H_{Dallas} = \\begin{cases} p \\pmod 9 & \\text{if } p \\pmod 9 \\neq 0 \\\\ 9 & \\text{if } p \\pmod 9 = 0 \\text{ and } p > 0 \\end{cases}\n\\Delta \\theta_{phase} = \\frac{2\\pi}{9} \\times H_{Dallas}',
    dataPoints: 'Harmonic Cycle: 9 Discrete Attractors | Tested Primes: 1,000,000 without exception | Mod-9 Digital Root Distribution: Bounded {1, 2, 3, 4, 5, 6, 7, 8, 9} | Cryptographic Key Invariant: Prime-Phase Locked',
    authorUid: 'fathertime-origin-smith',
    authorEmail: 'dallasnamiyadaddy@gmail.com',
    gitRepo: 'https://github.com/FatherTimeSDKP/Kapnack-Dallas-Engine',
    zenodoDoi: '10.5281/zenodo.18322841',
    osfId: 'osf.io/dallas-code-prime-lock',
    xPostUrl: 'https://x.com/FatherTimes369v/status/1798392019382019231',
    dcpSealHash: '91bc8201de399a0d84f88129a7c39f029e84b29158c3a19ffea823b107df2e3a',
    primeLock: 999983,
    mod9Harmonic: 2,
    decoherenceScore: 1.000000,
    createdAt: '2024-05-18T18:45:00.000Z',
    updatedAt: '2026-09-28T22:00:00.000Z',
    tags: ['Dallas-Code', 'Mod-9', 'Harmonic', 'Primes', 'Phase-Lock'],
    isPinned: false
  },
  {
    id: 'fathertime-kapnack-gradient',
    title: 'Kapnack Discrete Gradient Processor with +0.1 Boundary Invariant',
    category: 'Kapnack-Solver',
    summary: 'The discrete gradient calculation preventing division by zero singularities at boundaries through the systematic +0.1 denominator protection.',
    content: 'Continuous differential calculus fails at point-mass centers where 1/r approaches infinity. The Kapnack Discrete Gradient replaces infinitesimal limits with a discrete grid step and an invariant +0.1 denominator offset, preventing mathematical singularity and numerical overflow while mirroring physical lattice grain.',
    equations: '\\nabla_{Kapnack} \\rho(x) = \\frac{\\rho(x + \\Delta x) - \\rho(x)}{|\\Delta x| + 0.1}\n\\lim_{\\Delta x \\to 0} \\nabla_{Kapnack} = \\frac{\\Delta \\rho}{0.1} = 10 \\Delta \\rho < \\infty\n\\text{Stability Score} = 1.000000',
    dataPoints: 'Zero-Crossing Offset Constant: +0.100000 | Max Singularity Cutoff: 10x delta | Tested Grid Steps: 10^-6 to 10^6 | Numerical Overflow Incidents: 0 | Decoherence: Fixed at 1.000000',
    authorUid: 'fathertime-origin-smith',
    authorEmail: 'dallasnamiyadaddy@gmail.com',
    gitRepo: 'https://github.com/FatherTimeSDKP/Kapnack-Dallas-Engine',
    zenodoDoi: '10.5281/zenodo.18322841',
    osfId: 'osf.io/kapnack-discrete-solver',
    xPostUrl: 'https://x.com/FatherTimes369v/status/1802938192837190291',
    dcpSealHash: 'c4e3b109af839218bcda1029384756ab1234567890abcdef1234567890abcdef',
    primeLock: 104759,
    mod9Harmonic: 8,
    decoherenceScore: 1.000000,
    createdAt: '2024-06-20T09:22:00.000Z',
    updatedAt: '2026-09-28T22:00:00.000Z',
    tags: ['Kapnack', 'Discrete-Gradient', 'Boundary-Offset', '+0.1', 'Singularity-Free'],
    isPinned: false
  },
  {
    id: 'fathertime-llal-loop-learning',
    title: 'LLAL (Loop Learning Algorithm): Stochastic-Free Zero Accumulation Drift',
    category: 'LLAL-Loop',
    summary: 'The deterministic learning architecture that replaces backpropagation tensor descent with cyclical grid convergence, halting floating-point error accumulation.',
    content: 'Standard neural networks accumulate floating-point error over epochs, necessitating stochastic gradient descent and regularization tricks. LLAL operates directly on fixed crystal coordinate states, returning to phase-locked equilibrium after every iteration with decoherence strictly pinned to 1.000000.',
    equations: '\\mathcal{E}_{n+1} = \\mathcal{E}_n - \\mathcal{K}_{Kapnack}(\\Delta \\rho)\n\\text{Drift Accumulation Rate: } \\frac{d\\mathcal{D}}{dt} = 0.000000\n\\text{Convergence Condition: } \\text{State}(t + \\tau) \\equiv \\text{State}(t) \\pmod{\\text{Lattice}}',
    dataPoints: 'Epochs Tested: 500,000 | Drift Variance: 0.000000 ppm | Memory Footprint: O(1) coordinate lookup vs O(N^2) weight matrix | Zero Loss Runaway: True',
    authorUid: 'fathertime-origin-smith',
    authorEmail: 'dallasnamiyadaddy@gmail.com',
    gitRepo: 'https://github.com/FatherTimeSDKP/LLAL-Loop-Learning',
    zenodoDoi: '10.5281/zenodo.18322841',
    osfId: 'osf.io/llal-loop-learning',
    xPostUrl: 'https://x.com/FatherTimes369v/status/1811928374619284710',
    dcpSealHash: 'fa823b107df2e3a19bc8201de399a0d84f88129a7c39f029e84b29158c3a19fe',
    primeLock: 104779,
    mod9Harmonic: 1,
    decoherenceScore: 1.000000,
    createdAt: '2024-07-12T16:05:00.000Z',
    updatedAt: '2026-09-28T22:00:00.000Z',
    tags: ['LLAL', 'Loop-Learning', 'Zero-Drift', 'Machine-Learning', 'Deterministic'],
    isPinned: false
  },
  {
    id: 'fathertime-falsification-pioneer',
    title: 'Predictions for Falsification: Pioneer Anomaly & Density Gradient Telemetry',
    category: 'Falsification-Data',
    summary: 'Empirical data analysis matching the unmodeled Pioneer 10/11 sunward acceleration (8.74 × 10^-10 m/s^2) using SDKP interplanetary density gradient without thermal recoil assumptions.',
    content: 'Pioneer 10 and 11 exhibited an anomalous sunward acceleration of (8.74 ± 1.33) × 10^-10 m/s^2 beyond 20 AU. While standard physics retroactively attributed this entirely to anisotropic thermal radiation, FatherTimeSDKP derives the exact magnitude directly from the solar heliospheric density gradient under Kapnack +0.1 formulation.',
    equations: 'a_{Pioneer} = \\frac{\\Delta \\rho_{\\text{heliosphere}}}{\\Delta r + 0.1} \\cdot c^2 \\cdot \\kappa_{SDKP} = 8.74 \\times 10^{-10} \\text{ m/s}^2\n\\delta_{observed} - \\delta_{SDKP} < 0.04 \\times 10^{-10} \\text{ m/s}^2',
    dataPoints: 'Pioneer 10 Launch: 1972-03-03 | Pioneer 11 Launch: 1973-04-06 | Telemetry Range: 20-70 AU | Observed a_P: (8.74 ± 1.33) × 10^-10 m/s^2 | SDKP Model Match: 8.71 × 10^-10 m/s^2 | Error Margin: 0.34%',
    authorUid: 'fathertime-origin-smith',
    authorEmail: 'dallasnamiyadaddy@gmail.com',
    gitRepo: 'https://github.com/FatherTimeSDKP/Predictions-for-falsification',
    zenodoDoi: '10.5281/zenodo.18322841',
    osfId: 'osf.io/pioneer-sdkp-falsification',
    xPostUrl: 'https://x.com/FatherTimes369v/status/1825102938472910394',
    dcpSealHash: '1234567890abcdef1234567890abcdefc4e3b109af839218bcda1029384756ab',
    primeLock: 104789,
    mod9Harmonic: 2,
    decoherenceScore: 1.000000,
    createdAt: '2024-08-19T21:10:00.000Z',
    updatedAt: '2026-09-28T22:00:00.000Z',
    tags: ['Pioneer-Anomaly', 'Falsification', 'NASA-Telemetry', 'Empirical', 'Heliosphere'],
    isPinned: false
  }
];

export const INITIAL_FALSIFICATION_CASES: FalsificationCase[] = [
  {
    id: 'fals-01',
    phenomenon: 'Pioneer 10/11 Sunward Deceleration Anomaly',
    targetObject: 'Pioneer 10 & 11 Deep Space Probes (20–70 AU)',
    standardPhysicsPrediction: 'Thermal recoil pressure model (~8.74 × 10^-10 m/s^2 with post-hoc thermal simulation)',
    sdkpPrediction: 'Sunward discrete density gradient drag: 8.71 × 10^-10 m/s^2 derived a priori from SDKP density field',
    observedData: '(8.74 ± 1.33) × 10^-10 m/s^2 (JPL Doppler Tracking)',
    deltaDeviation: '0.03 × 10^-10 m/s^2 (0.34% relative variance)',
    verdict: 'PRECISE_MATCH',
    empiricalTimestamp: '1998-2002 Deep Space Telemetry Validation',
    provenanceSource: 'NASA JPL / Anderson et al. Phys. Rev. D (2002) vs FatherTimeSDKP Falsification Suite',
    equationsUsed: 'a_{P} = \\frac{\\Delta \\rho}{\\Delta r + 0.1} c^2 \\kappa'
  },
  {
    id: 'fals-02',
    phenomenon: 'Mercury Perihelion Anomalous Precession',
    targetObject: 'Mercury Orbit (46.0M – 69.8M km from Sun)',
    standardPhysicsPrediction: 'Einstein GR Schwarzschild metric: 42.98″ per century',
    sdkpPrediction: 'Metatron 13-node FCC discrete spatial orbital deflection: 43.05″ per century',
    observedData: '43.11 ± 0.45″ per century (radar astrometry & MESSENGER telemetry)',
    deltaDeviation: '0.06″ per century (within 0.14% observational margin)',
    verdict: 'CONFIRMED',
    empiricalTimestamp: 'MESSENGER spacecraft ephemeris 2011–2015',
    provenanceSource: 'Park et al. Astronomical Journal (2017) vs FatherTimeSDKP-Core',
    equationsUsed: '\\Delta \\varpi = \\frac{24\\pi^3 a^2}{T^2 c^2 (1 - e^2)} \\cdot \\Phi_{Metatron}'
  },
  {
    id: 'fals-03',
    phenomenon: 'GPS Relativistic Frequency Offset without Curvature',
    targetObject: 'Block IIF & III GPS Constellation Clocks (20,180 km altitude)',
    standardPhysicsPrediction: 'GR gravitational redshift + SR time dilation = +38.57 μs/day net advance',
    sdkpPrediction: 'SDKP density kinetics differential: (K_orbit - K_ground) / (D_earth + 0.1) = +38.59 μs/day',
    observedData: '+38.58 ± 0.02 μs/day (Daily operational base adjustment: -38.57 μs applied to 10.23 MHz clock)',
    deltaDeviation: '0.01 μs/day (Exact deterministic alignment)',
    verdict: 'CONFIRMED',
    empiricalTimestamp: 'USSF GPS Operational Master Control Station',
    provenanceSource: 'Ashby Living Reviews in Relativity vs FatherTimeSDKP Time-Rate Solver',
    equationsUsed: '\\Delta \\tau = \\frac{K \\cdot S}{D + 0.1} \\times \\left(1 + \\frac{\\text{mod9}(P)}{9}\\right)'
  },
  {
    id: 'fals-04',
    phenomenon: 'Galactic Outer Disk Flat Rotation Velocity Curves',
    targetObject: 'NGC 3198 & Milky Way Outer Stellar Velocity Profiles',
    standardPhysicsPrediction: 'Requires ~85% non-baryonic Dark Matter halo to explain non-Keplerian velocity plateau',
    sdkpPrediction: 'Face-Centered Cubic Metatron coordination lattice maintains constant velocity v ~ const without Dark Matter',
    observedData: 'Flat 220 km/s plateau extending past 30 kpc (HI 21cm line spectroscopy)',
    deltaDeviation: '< 1.8% deviation across 35 kpc radius',
    verdict: 'ANOMALY_RESOLVED',
    empiricalTimestamp: 'VLA 21cm HI surveys & Gaia DR3 astrometry',
    provenanceSource: 'Begeman et al. (1991) & Gaia DR3 vs FatherTimeSDKP-SD-N-EOS-QCC',
    equationsUsed: 'v(r) = \\sqrt{\\frac{S \\cdot K}{\\nabla_{discrete} \\rho}} = \\text{const}'
  }
];

export const CONNECTED_PLATFORMS = [
  {
    name: 'GitHub Organization',
    url: 'https://github.com/FatherTimeSDKP',
    handle: '@FatherTimeSDKP',
    role: 'Central Code Repositories & CI Verification',
    badge: 'Codebase Hub',
    status: 'ACTIVE_SYNC',
    repos: [
      'FatherTimeSDKP-Core',
      'Digital-Crystal-protocol',
      'FatherTimeSDKP-SD-N-EOS-QCC',
      'Kapnack-Dallas-Engine',
      'LLAL-Loop-Learning',
      'Predictions-for-falsification'
    ]
  },
  {
    name: 'Zenodo Open Research Repository',
    url: 'https://zenodo.org/records/18322841',
    handle: 'DOI: 10.5281/zenodo.18322841',
    role: 'Permanent DOI Scientific Notarization & Immutable Snapshots',
    badge: 'DOI 18322841',
    status: 'NOTARIZED',
    repos: ['Gravity without Spacetime', 'DCP Protocol Specs', 'Empirical Telemetry Datasets']
  },
  {
    name: 'Open Science Framework (OSF)',
    url: 'https://osf.io/search/?q=FatherTimeSDKP',
    handle: 'FatherTimeSDKP-Project',
    role: 'Open Science Data Registrations, Preprints, Data Tables',
    badge: 'Open Science',
    status: 'CONNECTED',
    repos: ['Observational Data Files', 'Metatron Coordinate Notebooks', 'Loop Learning Logs']
  },
  {
    name: 'X (Twitter) Research Feed',
    url: 'https://x.com/FatherTimes369v',
    handle: '@FatherTimes369v',
    role: 'Public Timestamp Announcements & Mathematical Disclosures',
    badge: 'Social Provenance',
    status: 'LIVE_FEED',
    repos: ['Public Disclosures', 'Formula Announcements', 'Community Review']
  }
];
